CREATE TABLE IF NOT EXISTS student_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(50) NOT NULL,
  gender_pref VARCHAR(20),
  mode VARCHAR(20) NOT NULL,
  location VARCHAR(255) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  level VARCHAR(255) NOT NULL,
  budget VARCHAR(100) NOT NULL,
  status VARCHAR(20) DEFAULT 'open',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
